//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moss.Standard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moss.Standard.Resources.AppSettings", typeof(AppSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory.
        /// </summary>
        internal static string DirectoryModeOption {
            get {
                return ResourceManager.GetString("DirectoryModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        internal static string EndOption {
            get {
                return ResourceManager.GetString("EndOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ExperimentalOption {
            get {
                return ResourceManager.GetString("ExperimentalOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        internal static string MaximumFilesToShowOption {
            get {
                return ResourceManager.GetString("MaximumFilesToShowOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxmatches.
        /// </summary>
        internal static string MaximumMatchesOption {
            get {
                return ResourceManager.GetString("MaximumMatchesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7690.
        /// </summary>
        internal static string MossPort {
            get {
                return ResourceManager.GetString("MossPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moss.stanford.edu.
        /// </summary>
        internal static string MossServer {
            get {
                return ResourceManager.GetString("MossServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string QueryOption {
            get {
                return ResourceManager.GetString("QueryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moss.
        /// </summary>
        internal static string UserIdOption {
            get {
                return ResourceManager.GetString("UserIdOption", resourceCulture);
            }
        }
    }
}
